# testing trigger to get the content of a github action into
# the filesystem for a step
parameters:
  event_payload:
    description: "The full json payload from the incoming github event"

triggers:
  - name: github-event
    source:
      type: webhook
      image: relaysh/github-trigger-event-sink
    binding:
      parameters:
        event_payload: !Data event_payload

steps:
  - name: dump-payload
    image: relaysh/core
    spec:
      event_payload: !Parameter event_payload
    input:
      - mkdir -p /github/workflow
      - ni get | jq .event_payload > /github/workflow/event.json
      - cat /github/workflow/event.json

